// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp6ncnzFA3p8OPccC9zU2bmDGP3_RPcTA',
    appId: '1:29868442133:web:32a1a9dcde82263356041c',
    messagingSenderId: '29868442133',
    projectId: 'chat-app-50cb0',
    authDomain: 'chat-app-50cb0.firebaseapp.com',
    storageBucket: 'chat-app-50cb0.appspot.com',
    measurementId: 'G-9TDF1TERFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6tOn80L1kSDLD-5OGtvCr7t4GI3kjv9I',
    appId: '1:29868442133:android:236c9c1217d0029056041c',
    messagingSenderId: '29868442133',
    projectId: 'chat-app-50cb0',
    storageBucket: 'chat-app-50cb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdUozQxN0O5K4fPx03rVfNngROFYP3YRY',
    appId: '1:29868442133:ios:ecc1811513d4e70d56041c',
    messagingSenderId: '29868442133',
    projectId: 'chat-app-50cb0',
    storageBucket: 'chat-app-50cb0.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
